In [7]:
import numpy as np

# Generating Random Numbers

In [8]:
r_1 = np.random.randint(1, 20, size =(2))
r_1

array([ 5, 17], dtype=int32)

In [9]:
print(r_1)

[ 5 17]


In [10]:
r_2 = np.random.randint(1, 20, size=(1, 2,))
r_2

array([[18, 19]], dtype=int32)

In [11]:
print(r_2)

[[18 19]]


In [12]:
r_3 = np.random.rand(2, 1)
r_3

array([[0.00467514],
       [0.70369997]])

In [13]:
print(r_3)

[[0.00467514]
 [0.70369997]]


In [14]:
r_4 = np.random.randint(20, 100, size=(4, 5))
r_4

array([[79, 51, 93, 54, 99],
       [95, 50, 53, 56, 81],
       [43, 84, 84, 56, 51],
       [73, 45, 71, 38, 22]], dtype=int32)

In [15]:
print(r_4)

[[79 51 93 54 99]
 [95 50 53 56 81]
 [43 84 84 56 51]
 [73 45 71 38 22]]


In [16]:
r_5 = np.random.rand(4, 5)
r_5

array([[0.37317918, 0.36258366, 0.29885141, 0.83682967, 0.08051186],
       [0.71724758, 0.71889882, 0.74351431, 0.05913451, 0.59582472],
       [0.10344199, 0.88700186, 0.76399889, 0.56275549, 0.58216639],
       [0.38204955, 0.13100102, 0.43788664, 0.50071024, 0.94158416]])

In [17]:
print(r_5)

[[0.37317918 0.36258366 0.29885141 0.83682967 0.08051186]
 [0.71724758 0.71889882 0.74351431 0.05913451 0.59582472]
 [0.10344199 0.88700186 0.76399889 0.56275549 0.58216639]
 [0.38204955 0.13100102 0.43788664 0.50071024 0.94158416]]


# Generating Random Choices from an Array

In [18]:
students = np.array(['jordan', 'hassan', 'jacob', 'rodolfo', 'vieri', 'symone', 'vanessa', 'craig', 'zainab', 'anthony', 'jaela', 'caitlan'])

In [19]:
call_on = np.random.choice(students)
call_on

np.str_('symone')

In [20]:
print(call_on)

symone


In [21]:
breakout_groups = np.random.choice(students, size=(3, 4))
breakout_groups

array([['vanessa', 'hassan', 'zainab', 'rodolfo'],
       ['jacob', 'vanessa', 'jordan', 'symone'],
       ['craig', 'craig', 'craig', 'vieri']], dtype='<U7')

In [22]:
print(breakout_groups)
# This would not be an effective way to assign breakout groups because even though the students are chosen randomly, there are repeated names.They can't be at one breakout room once while in a different breakout room more than once.

[['vanessa' 'hassan' 'zainab' 'rodolfo']
 ['jacob' 'vanessa' 'jordan' 'symone']
 ['craig' 'craig' 'craig' 'vieri']]


In [26]:
call_on_weighted = np.random.choice(students, p=[0.0, 0.3, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07], size=(5))
call_on_weighted
                

array(['craig', 'hassan', 'vanessa', 'anthony', 'hassan'], dtype='<U7')

In [29]:
# I chose the p values I assigned to each student for at least one student to never occur as it has a p value of zero, one student is more likely to occur as it has a p value of 30%. For the rest of the 10 student I had to give them a p value of 7% each to make the total of all probability values equal to 1.

# Generating a Normal Distribution 

In [27]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
bell_curve

array([[ 4.50598784, 13.06000451,  0.2044867 ,  5.11714981,  7.17642707],
       [12.24394091,  7.18940246, -2.00130211, 10.32550159,  2.80481957],
       [13.55667333, 11.2689616 , 17.47486185,  8.88732212, 13.38063276],
       [15.24571776,  8.04765886,  8.04977527, 10.17516284, 14.47041829]])

In [28]:
print(bell_curve)

[[ 4.50598784 13.06000451  0.2044867   5.11714981  7.17642707]
 [12.24394091  7.18940246 -2.00130211 10.32550159  2.80481957]
 [13.55667333 11.2689616  17.47486185  8.88732212 13.38063276]
 [15.24571776  8.04765886  8.04977527 10.17516284 14.47041829]]
