In [1]:
import numpy as np

# Generating Random Numbers

In [4]:
r_1 = np.random.randint(1, 20, size =(2))
r_1

array([11, 13], dtype=int32)

In [5]:
print(r_1)

[11 13]


In [10]:
r_2 = np.random.randint(1, 20, size=(1, 2,))
r_2

array([[5, 2]], dtype=int32)

In [11]:
print(r_2)

[[5 2]]


In [12]:
r_3 = np.random.rand(2, 1)
r_3

array([[0.77271829],
       [0.9276177 ]])

In [13]:
print(r_3)

[[0.77271829]
 [0.9276177 ]]


In [14]:
r_4 = np.random.randint(20, 100, size=(4, 5))
r_4

array([[83, 41, 64, 72, 66],
       [55, 86, 54, 70, 92],
       [58, 62, 46, 54, 55],
       [94, 83, 85, 23, 20]], dtype=int32)

In [15]:
print(r_4)

[[83 41 64 72 66]
 [55 86 54 70 92]
 [58 62 46 54 55]
 [94 83 85 23 20]]


In [16]:
r_5 = np.random.rand(4, 5)
r_5

array([[0.22931695, 0.29828885, 0.36567119, 0.15758216, 0.83182774],
       [0.56066224, 0.17015448, 0.52218711, 0.56316624, 0.99268641],
       [0.3482948 , 0.12862425, 0.36248982, 0.6673747 , 0.97582187],
       [0.78927412, 0.65592142, 0.51762284, 0.65257535, 0.71908297]])

In [17]:
print(r_5)

[[0.22931695 0.29828885 0.36567119 0.15758216 0.83182774]
 [0.56066224 0.17015448 0.52218711 0.56316624 0.99268641]
 [0.3482948  0.12862425 0.36248982 0.6673747  0.97582187]
 [0.78927412 0.65592142 0.51762284 0.65257535 0.71908297]]


# Generating Random Choices from an Array

In [36]:
students = np.array(['jordan', 'hassan', 'jacob', 'rodolfo', 'vieri', 'symone', 'vanessa', 'craig', 'zainab', 'anthony', 'jaela', 'caitlan'])

In [37]:
call_on = np.random.choice(students)
call_on

np.str_('vieri')

In [38]:
print(call_on)

vieri


In [39]:
breakout_groups = np.random.choice(students, size=(3, 4))
breakout_groups

array([['vanessa', 'zainab', 'hassan', 'vieri'],
       ['rodolfo', 'hassan', 'vanessa', 'vieri'],
       ['hassan', 'rodolfo', 'rodolfo', 'jaela']], dtype='<U7')

In [40]:
print(breakout_groups)
# This would not be an effective way to assign breakout groups because even though the students are chosen randomly, there are repeated names.They can't be at one breakout room once while in a different breakout room more than once.

[['vanessa' 'zainab' 'hassan' 'vieri']
 ['rodolfo' 'hassan' 'vanessa' 'vieri']
 ['hassan' 'rodolfo' 'rodolfo' 'jaela']]


In [42]:
call_on_weighted = np.random.choice(['vanessa', 'zainab', 'hassan', 'vieri', 'jaela'], p=[0.0, 0.3, 0.2, 0.1, 0.4], size=(5))
call_on_weighted
                

array(['jaela', 'zainab', 'jaela', 'jaela', 'zainab'], dtype='<U7')

In [ ]:
# I chose the p values I assigned to each student for at least one student to never occur as it has a p value of zero, one student is more likely to occur as it has a p value of 30%, another student has a higher probability of occurence since they have p value of 40%. One of the students has a p value of 20% and another student who has a p value of 10% of occurence. Total of all probability values equal to 1.

In [43]:
print(call_on_weighted)

['jaela' 'zainab' 'jaela' 'jaela' 'zainab']


# Generating a Normal Distribution 

In [44]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
bell_curve

array([[12.23127795,  7.3668304 , 14.31159762, 13.70707309,  6.41158549],
       [ 4.39083526, 12.52029572,  6.8084508 , 13.8035415 ,  4.99712445],
       [ 5.53269848,  7.595068  ,  8.54123044, 11.67264863, 17.95858532],
       [11.72786133, 14.85128755, 11.5607248 , 13.78635778, 13.18479485]])

In [45]:
print(bell_curve)

[[12.23127795  7.3668304  14.31159762 13.70707309  6.41158549]
 [ 4.39083526 12.52029572  6.8084508  13.8035415   4.99712445]
 [ 5.53269848  7.595068    8.54123044 11.67264863 17.95858532]
 [11.72786133 14.85128755 11.5607248  13.78635778 13.18479485]]
